-- Supabase SQL Schema for FinalOrbit Leaderboard & 1v1 Duel Arena

-- 1. Leaderboard Table
create table if not exists leaderboard (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pilot_name text not null default 'PILOT',
  score integer not null default 0,
  wave integer not null default 1
);

alter table leaderboard enable row level security;

create policy "Allow public read"
  on leaderboard for select
  using (true);

create policy "Allow public insert"
  on leaderboard for insert
  with check (true);

-- 2. Create 1v1 Matchmaking Rooms Table
create table if not exists public.duel_rooms (
  id uuid default gen_random_uuid() primary key,
  room_code text unique not null,
  host_callsign text not null,
  challenger_callsign text,
  status text not null default 'WAITING', -- 'WAITING', 'IN_GAME', 'FINISHED'
  winner_callsign text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table public.duel_rooms enable row level security;

-- 4. Open Access Policies (Allow players to find, create, and join match rooms)
create policy "Allow public read access on duel_rooms"
  on public.duel_rooms for select using (true);

create policy "Allow public insert on duel_rooms"
  on public.duel_rooms for insert with check (true);

create policy "Allow public update on duel_rooms"
  on public.duel_rooms for update using (true);

-- 5. Enable Supabase Realtime for the table
alter publication supabase_realtime add table public.duel_rooms;
