-- Supabase SQL Schema for FinalOrbit Leaderboard
create table if not exists leaderboard (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pilot_name text not null default 'PILOT',
  score integer not null default 0,
  wave integer not null default 1
);

-- Enable read access for everyone and insert access for players
alter table leaderboard enable row level security;

create policy "Allow public read"
on leaderboard for select
using (true);

create policy "Allow public insert"
on leaderboard for insert
with check (true);
